services:

  web:
    build: ./frontend
    container_name: shoplitex-frontend
    ports:
      - 5173:5173
    depends_on:
      - api
    env_file:
      - ./frontend/.env

  api:
    build: ./backend
    container_name: shoplitex-backend
    ports: 
      - 10000:10000
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./backend/media:/app/media

  db:
    image: postgres:15-alpine
    container_name: shoplite-db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-123456}
      POSTGRES_DB: ${DB_NAME:-shop_db}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  ngrok:
    image: ngrok/ngrok:latest
    
    container_name: shop_ngrok
    command:
      - "http"
      - "--domain=${NGROK_DOMAIN}"
      - "api:10000"
    env_file:
      - .env
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    depends_on:
      - api